#!/usr/bin/env python3

# pylint: disable=too-many-arguments, no-value-for-parameter

import logging
from json import JSONDecoder
from pathlib import Path

import click
import click_log
from aptible.api import AptibleApi
from aptible.api.model import EmptyResource

logger = logging.getLogger(__name__)
click_log.basic_config(logger)


@click.command()
@click.option('-a', '--api-url', type=str, default="https://api.aptible.com")
@click.option('-p', '--tokens-path', type=Path, default="~/.aptible/tokens.json")
@click.option('-k', '--tokens-path-key', type=str, default="https://auth.aptible.com")
@click.option('-t', '--token', type=str)
@click.option('-u', '--username', type=str)
@click.option('-P', '--password', type=str)
@click_log.simple_verbosity_option(logger)
@click.argument('backup_ids', type=int, required=True, nargs=-1)
def main(api_url, tokens_path, tokens_path_key, token, username, password, backup_ids):
    aptible_api = AptibleApi()

    logger.info("Authenticating to Aptible API")
    if token:
        aptible_api.authorize(token=token, email=None, password=None)

    elif username and password:
        aptible_api.authorize(email=username, password=password)

    else:
        token_path = Path(tokens_path).expanduser()
        token_json = JSONDecoder().decode(token_path.read_text())
        token = token_json[tokens_path_key]
        aptible_api.authorize(token=token, email=None, password=None)

    if not aptible_api.authorized:
        logger.error("Authentication to Aptible API failed")
        raise click.UsageError("Authentication to Aptible API failed")

    for backup_id in backup_ids:
        backup = aptible_api.fetch_backup(backup_id)

        if isinstance(backup, EmptyResource):
            logger.info("Backup(id=%d) not found ... skipping.", backup_id)
            continue

        logger.info("Backup(id=%d) found ... purging.", backup_id)
        operation = backup.create_operation(type="purge", status="queued")


if __name__ == '__main__':
    main()
